// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reader.Infrastructures.Sql;

#nullable disable

namespace Reader.Infrastructures.Migrations
{
    [DbContext(typeof(GisDbContext))]
    [Migration("20231204064013_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Reader.Infrastructures.Sql.Entities.SqlGisObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("GisInfoTmpId");

                    b.Property<int?>("GisInfoGeoCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .HasColumnType("TEXT")
                        .HasColumnName("GisInfoJson");

                    b.Property<int>("LayerCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GisSymbolCode");

                    b.Property<string>("LayerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeLatLngStr")
                        .HasColumnType("TEXT")
                        .HasColumnName("GisInfoShapeLatLngStr");

                    b.Property<string>("ShapeStr")
                        .HasColumnType("TEXT")
                        .HasColumnName("GisInfoShapeStr");

                    b.HasKey("Id");

                    b.ToTable("t_GisInfoTmp", "Gis");
                });
#pragma warning restore 612, 618
        }
    }
}
